### ISSUE TITLE
Error presenting Challenge: Unable to login to netcup API

### ISSUE THREAD

**Issue by teksuo** [aellwein/cert-manager-webhook-netcup#10]
Hi there!

First of all: thanks Alex for such a great component, it has been very helpful for me :-)

I have been using this webhook for the last year (every single version of it) along with **cert-manager 1.9.1** at different cloud providers (managed and self-managed) and has always worked perfectly.

Sadly, since last release(**1.0.16**), new provisioned clusters(at every provider) are getting an error when presenting the DNS challenge to Netcup, more precisely, describing the Challenge object outputs:

`Error presenting challenge: unable to login to netcup API: Post "https://ccp.netcup.net/run/webservice/servers/endpoint.php?JSON": tls: failed to verify certificate: x509: certificate signed by unknown authority`

What I've tried without success:

- Upgrading **cert-manager** to every version up to **1.12.2**
- Rotating Netcup API password

What I've tried with success:
- Downgrading **cert-manager-webhook-netcup** to **1.0.15**

So, it looks like everything points at this new release. 

Please tell me if I can support you with further testing of this issue.

Again, thanks a lot for your precious time!

**Comment by aellwein** [comment]
Hi @teksuo, 

thank you for the warm words and for the report. 
Seems like a bug was slipped through in the last release. :-(

I think i understand what is going on here: 
with the last commit i switched Docker images from Alpine Linux to busybox
(i wanted to use a less vulnerable and even more lightweight base Docker image), 
but apparently busybox is missing default CA certificates (so the netcup's cert issuer is not known/trusted). 
These CAs were installed in Alpine image with apk, i also need to include them into Busybox image.

Until now, it's perfectly fine to use 1.0.15, i'll try to come with a new release in the evening.

Thanks!

**Comment by aellwein** [comment]
a new release build will be started immediately.

**Comment by aellwein** [comment]
@teksuo the 1.0.17 is online. I've successfully tested with letsencrypt-staging, but it should do the same with letsencrypt-production endpoint. Have fun!

**Comment by Mik4sa** [comment]
@aellwein 
I'm using 1.0.17 and this does not seem to be fixed for me. I'm still getting the error messages:
`kubectl logs -n cert-manager cert-manager-bf8f6b86-4d9lw`

```
I0703 16:23:42.660393       1 dns.go:88] "cert-manager/challenges/Present: presenting DNS01 challenge for domain" resource_name="***-certificate-2wcnz-2621465800-3021163944" resource_namespace="cert-manager" resource_kind="Challenge" resource_version="v1" dnsName="***.com" type="DNS-01" resource_name="***-certificate-2wcnz-2621465800-3021163944" resource_namespace="cert-manager" resource_kind="Challenge" resource_version="v1" domain="***.com"
E0703 16:23:42.662686       1 controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="unable to login to netcup API: Post \"https://ccp.netcup.net/run/webservice/servers/endpoint.php?JSON\": tls: failed to verify certificate: x509: certificate signed by unknown authority" key="cert-manager/***-certificate-2wcnz-2621465800-224046942"
```

Looking at the changes since 1.0.17 I see this commit: https://github.com/aellwein/cert-manager-webhook-netcup/commit/d399c61efeb96c5000e9661f1ffe959ac58793a4
So this is still missing in 1.0.17?

Am I missing anything?

**Comment by aellwein** [comment]
@Mik4sa seems that i accidently deployed an older version with actions pipeline -> will release a new one. Sorry

**Comment by Mik4sa** [comment]
No problem. This is nothing time critical :)

**Comment by aellwein** [comment]
@Mik4sa i've just rebuilt the Docker images so you can use 1.0.17. I will correct the release tag to reflect the correct commit. Thanks.

**Comment by Mik4sa** [comment]
Great! I'll have a look at it by tomorrow

**Comment by Mik4sa** [comment]
@aellwein Should be fine now. Thank you for your fast reply and help :)
