### ISSUE TITLE
Publish on Github's container registry

### ISSUE THREAD

**Issue by mrueg** [aellwein/cert-manager-webhook-netcup#28]
Currently this is published on dockerhub only, would it be possible to publish a container image on ghcr as well?

**Comment by aellwein** [comment]
Hi Manuel,
sure, i can migrate the images to ghcr.io. 

P.S.: just for curiosity: is the ghcr more reliable/preferred than the Docker Hub?

**Comment by mrueg** [comment]
The reason for this request is mainly https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by aellwein** [comment]
Pipeline is adapted, will do the 1.0.19 release in a second.

**Comment by mrueg** [comment]
Thank you!

**Comment by aellwein** [comment]
> Thank you! Can you make the package/repository public?

What do you mean by public? I could pull the image from my local machine without a login:
``docker pull ghcr.io/aellwein/cert-manager-webhook-netcup:1.0.19``

Or am i missing something?

**Comment by mrueg** [comment]
Yep, that is what I meant. Thank you :)
